---
name: BIOPYPIR-APPROVED
on: [push,pull_request] 
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7] # changed tensorflow from 1.7.0 to 1.15.2
        os:  [ubuntu-latest,macOS-latest] # macports version of HDF5 is bad
    steps:
    - name: STEP 1. Check-Out Repo 
      uses: actions/checkout@v2     
    #===============================================#
    - name: STEP 2. Set-Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: custom linter
      uses: benstear/python-pylint-github-action@master
      id: linter
      with:
        package_name: desc
        verbosity: score_only

    #===============================================#
    - name: STEP 3. Install dependencies
      run: |
       pip install --upgrade pip setuptools wheel
       sudo apt-get install libhdf5-dev
       echo '###############'
       pip install .
       
     #pip install python-coveralls
     #pip install coveralls
     #pip install junit2html
       
       
    - name: Test Build
      run: |
        python3 setup.py test
        ls -a
        echo #################################
        cd dist
        ls -a
        echo #################################
        
    - name: STEP 7. Zip Artifacts
      run: |
        zip artifacts.zip pylint-report.txt
    #===============================================#
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifacts.zip
        path: artifacts.zip
